atividades/urls.py
from django.contrib import admin
from django.urls import path
from .views import atividade, show, edit, update, destroy
urlpatterns = [
    path('atividade', atividade),
    path('show', show),
    path('edit/<int:id>', edit),
    path('update/<int:id>', update),
    path('delete/<int:id>', destroy),
]

dia_aberto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('atividades/', include('atividades.urls')),
    path('inscricoes/', include('inscricoes.urls')),
    path('utilizadores/', include('utilizadores.urls')),
    #path('utilizadores/', include('django.contrib.auth.urls')),
]

inscricoes/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from .views import ConsultarInscricoesListView, AlterarInscricao, ConsultarInscricaoResponsaveis, ConsultarInscricaoEscola
from django.urls import path
from django.views.generic import RedirectView
from inscricoes.views import ConsultarInscricao
from .views import AlterarInscricao, ConsultarInscricao, ConsultarInscricoes
from . import views

app_name = 'inscricoes'

urlpatterns = [
    path('api/atividades', views.AtividadesAPIView.as_view(), name="api-atividades"),
    path('api/escolas', views.EscolasAPIView.as_view(), name="api-escolas"),
    path('inscricaowizard', views.InscricaoWizard.as_view(),
         name='criar-inscricao-wizard'),
    path('alterar/<int:pk>', views.AlterarInscricaoWizard.as_view(),
         name='alterar-inscricao-wizard'),
    path('alterarinscricao', AlterarInscricao, name='alterar-inscricao'),
    path('<int:pk>', ConsultarInscricaoResponsaveis.as_view(),
         name='consultar-inscricao'),
    # url('$', ConsultarInscricaoEscola.detail, name='escola'),
    # url('escola', ConsultarInscricaoResponsaveis.escola, name='escola'),
    # url('consultar-inscricao-transporte',  ConsultarInscricaoResponsaveis.transporte, name="transporte"),
    # url('consultar-inscricao-almoço',  ConsultarInscricaoResponsaveis.almoço, name="almoço"),
    # url('consultar-inscricao-sessao',  ConsultarInscricaoResponsaveis.sessoes, name="sessao"),
    path("tabela/", ConsultarInscricoesListView.as_view()),
    # url('<int:pk>', ConsultarInscricaoEscola.as_view(), name='consultar-inscricao-escola'),
    # path('consultarinscricoes', ConsultarInscricoes, name='consultar-inscricoes'),

    path('<int:pk>', ConsultarInscricao.as_view(), name='consultar-inscricao'),
    path('consultarinscricoes', ConsultarInscricoes, name='consultar-inscricoes')
]

atividades/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models
from utilizadores.models import *
from coordenadores.models import *
from configuracao.models import *
from inscricoes.models import *
from notificacoes.models import *


class Anfiteatro(models.Model):
    # Field name made lowercase.
    espacoid = models.OneToOneField(
        Espaco, models.CASCADE, db_column='EspacoID', primary_key=True)
    # Field name made lowercase.
    espacoedificio = models.CharField(
        db_column='EspacoEdificio', max_length=255)

    class Meta:

        db_table = 'Anfiteatro'


class Arlivre(models.Model):
    # Field name made lowercase.
    espacoid = models.OneToOneField(
        Espaco, models.CASCADE, db_column='EspacoID', primary_key=True)
    # Field name made lowercase.
    espacoedificio = models.CharField(
        db_column='EspacoEdificio', max_length=255)

    class Meta:

        db_table = 'ArLivre'


class Atividade(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    nome = models.CharField(db_column='Nome', max_length=255)
    # Field name made lowercase.
    descricao = models.TextField(db_column='Descricao')
    publicosalvo = (("Ciencias e Tecnologia", "Ciências e Tecnologia"),
                    ("Linguas e Humanidades", "Linguas e Humanidades"), ("Economia", "Economia"))
    # Field name made lowercase.
    publicoalvo = models.CharField(
        db_column='Publicoalvo', max_length=255, choices=publicosalvo, default='')
    # Field name made lowercase.
    nrcolaboradoresnecessario = models.IntegerField(
        db_column='nrColaboradoresNecessario')
    tipos = (("Atividade Laboratorial", "Atividade Laboratorial"),
             ("Tertulia", "Tertulia"), ("Palestra", "Palestra"))
    # Field name made lowercase.
    tipo = models.CharField(db_column='Tipo', max_length=64,
                            choices=tipos, default='Palestra')
    # Field name made lowercase.
    estado = models.CharField(db_column='Estado', max_length=64)
    # Field name made lowercase.
    # TODO: Descomentar
    # coordenadorutilizadorid = models.ForeignKey(
    #     Coordenador, models.CASCADE, db_column='CoordenadorUtilizadorID')
    # professoruniversitarioutilizadorid = models.ForeignKey(
    #     ProfessorUniversitario, models.CASCADE, db_column='ProfessorUniversitarioUtilizadorID')  # Field name made lowercase.
    # Field name made lowercase.
    datasubmissao = models.DateTimeField(
        db_column='dataSubmissao', auto_now_add=True)
    # Field name made lowercase.
    dataalteracao = models.DateTimeField(
        db_column='dataAlteracao', auto_now=True)
    # Field name made lowercase.
    duracaoesperada = models.IntegerField(db_column='duracaoEsperada')
    # Field name made lowercase.
    participantesmaximo = models.IntegerField(db_column='participantesMaximo')
    # Field name made lowercase.
    # TODO: Descomentar
    # diaabertoid = models.ForeignKey(
    #     Diaaberto, models.CASCADE, db_column='diaAbertoID')
    # Field name made lowercase.
    # espacoid = models.ForeignKey(
    #     Espaco, models.CASCADE, db_column='EspacoID')
    # Field name made lowercase.
    # TODO: Descomentar
    # tema = models.ForeignKey('Tema', models.CASCADE,
    #                          db_column='Tema', blank=False, null=False)

    class Meta:

        db_table = 'Atividade'

    def get_fields(self):
        return [(field.name, field.value_to_string(self)) for field in Atividade._meta.fields]


class Materiais(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    atividadeid = models.ForeignKey(
        Atividade, models.DO_NOTHING, db_column='AtividadeID')
    nomematerial = models.CharField(
        db_column='nome', max_length=255, blank=True, null=True)

    class Meta:
        db_table = 'Materiais'


class Sessao(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    horarioid = models.ForeignKey(
        Horario, models.DO_NOTHING, db_column='HorarioID')
    # Field name made lowercase.
    ninscritos = models.IntegerField(db_column='NInscritos')
    # Field name made lowercase.
    vagas = models.IntegerField(db_column='Vagas')
    # Field name made lowercase.
    atividadeid = models.ForeignKey(
        Atividade, models.DO_NOTHING, 'sessoes', db_column='AtividadeID')
    # Field name made lowercase.
    dia = models.DateField(db_column='Dia', blank=True, null=True)

    class Meta:
        db_table = 'Sessao'


class Tema(models.Model):
    # Field name made lowercase.
    id = models.AutoField(db_column='ID', primary_key=True)
    # Field name made lowercase.
    tema = models.CharField(db_column='Tema', max_length=64)

    class Meta:

        db_table = 'Tema'

inscricoes/views.py
from atividades.models import Atividade, Sessao
import django_filters.rest_framework as djangofilters
from rest_framework import filters, pagination
from rest_framework.generics import ListCreateAPIView
from inscricoes.models import Escola, EscolaPortugal, Responsavel
from formtools.wizard.views import SessionWizardView
from django.http import HttpResponse, JsonResponse
import json
from django.forms.formsets import formset_factory
from django.views.generic import CreateView, DetailView, TemplateView
from .models import Inscricao, Inscricaotransporte, Inscricaoprato, Escola
from django.shortcuts import get_object_or_404, redirect, render
from django.core.exceptions import ValidationError
from . import models
from . import forms
from . import serializers
from utilizadores.forms import ParticipanteForm
from django.http.request import HttpRequest
from django.views.generic import CreateView, DetailView, TemplateView, ListView
from atividades.models import Sessao, Atividade
from .tables import InscricoesTable
from django_tables2 import RequestConfig, SingleTableView
from datetime import timezone


class AtividadesAPIView(ListCreateAPIView):

    class AtividadeFilter(djangofilters.FilterSet):
        nome = djangofilters.CharFilter(
            field_name="nome", lookup_expr='icontains')
        # min_price = filters.NumberFilter(field_name="price", lookup_expr='gte')
        # max_price = filters.NumberFilter(field_name="price", lookup_expr='lte')

        class Meta:
            model = Atividade
            fields = '__all__'

    class AtividadesPagination(pagination.PageNumberPagination):
        page_size = 1000
        page_size_query_param = 'page_size'
        max_page_size = 10000

    search_fields = '__all__'
    ordering_fields = '__all__'
    ordering = 'nome'
    filter_backends = (filters.SearchFilter,
                       filters.OrderingFilter, djangofilters.DjangoFilterBackend)
    queryset = Atividade.objects.all()
    serializer_class = serializers.AtividadeSerializer
    pagination_class = AtividadesPagination
    filterset_class = AtividadeFilter


class EscolasAPIView(ListCreateAPIView):
    search_fields = ['nome']
    filter_backends = (filters.SearchFilter, filters.OrderingFilter)
    queryset = EscolaPortugal.objects.all()
    serializer_class = serializers.EscolaSerializer
    ordering = 'nome'


class AlterarInscricaoWizard(SessionWizardView):

    form_list = [
        ('responsaveis', forms.ResponsavelForm),
        ('escola', forms.InscricaoForm),
        ('transporte', forms.TransporteForm),
        ('almoco', forms.TransporteForm),
        ('sessoes', forms.SessoesForm),
    ]

    def dispatch(self, request, *args, **kwargs):
        pk = self.kwargs['pk']
        inscricao = Inscricao.objects.get(pk=pk)
        escola = inscricao.escola
        self.instance_dict = {
            'responsaveis': Responsavel.objects.get(inscricao__pk=pk)
        }
        self.initial_dict = {
            'escola': {
                'nome': escola.nome,
                'local': escola.local,
                'ano': inscricao.ano,
                'turma': "A",
                'nalunos': inscricao.nalunos,
                'areacientifica': inscricao.areacientifica,
            }
        }
        return super(AlterarInscricaoWizard, self).dispatch(request, *args, **kwargs)

    def get_template_names(self):
        return [f'inscricoes/inscricao_wizard_{self.steps.current}.html']

    def done(self, form_list, form_dict, **kwargs):
        # Save to DB
        print(form_dict)
        return HttpResponse('<h1>Done!</h1>')


class InscricaoWizard(SessionWizardView):
    form_list = [
        ('responsaveis', forms.ResponsavelForm),
        ('escola', forms.InscricaoForm),
        ('transporte', forms.TransporteForm),
        ('almoco', forms.AlmocoForm),
        ('sessoes', forms.SessoesForm),
        ('submissao', forms.SubmissaoForm),
    ]


    def get_form_step_data(self, form):
        # print(f"DATA: {form.data}")
        # if(self.steps.current == 'sessoes'):
        #     print(f"SESSOES: {json.loads(form.data['sessoes-sessoes'])}")
        return form.data

    def get_template_names(self):
        return [f'inscricoes/inscricao_wizard_{self.steps.current}.html']

    def done(self, form_list, form_dict, **kwargs):
        # Save to DB
        sessoes = json.loads(form_dict['sessoes'].cleaned_data['sessoes'])
        responsaveis = form_dict['responsaveis'].save(commit=False)
        almoco = form_dict['almoco'].save(commit=False)
        inscricao = form_dict['escola'].save()
        for sessaoid in sessoes:
            if sessoes[sessaoid] > 0:
                inscricao_sessao = models.Inscricaosessao(sessao=Sessao.objects.get(pk=sessaoid), nparticipantes=sessoes[sessaoid], inscricao=inscricao)
                inscricao_sessao.save()
        responsaveis.inscricao = inscricao
        almoco.inscricao = inscricao
        responsaveis.save()
        almoco.save()
        return HttpResponse('<h1>Done!</h1>')


class ConsultarInscricaoResponsaveis(DetailView):
    model = Inscricao
    template_name = 'inscricoes/consultar_inscricao_responsaveis.html'

    def detail(request, inscricao_id):
        q = Inscricao.objects.filter(slug=inscricao_id)
        all_inscricoes = Inscricao.objects.all()
        all_inscricoescoletivas = Inscricaocoletiva.objects.all()
        qcoletivo = Inscricaocoletiva.objects.filter(slug=inscricao_id)
        qindividual = Inscricaoindividual.objects.filter(slug=inscricao_id)
        all_inscricoesindividuais = Inscricaoindividual.objects.all()
        qescola = EscolaForm.objects.filter(slug=inscricao_id)
        all_escolas = EscolaForm.objects.all()
        qparticipante = ParticipanteForm.objects.filter(slug=inscricao_id)
        all_participantes = ParticipanteForm.objects.all()
        qatividade = Atividade.objects.filter(slug=inscricao_id)
        all_atividades = Atividade.objects.all()
        qmenu = Inscricaoprato.objects.filter(slug=inscricao_id)
        all_menus = Inscricaoprato.objects.all()

        if q.exists():
            q = q.first()
        else:
            return HttpResponse('<h1>Page not found</h1>')

        if qcoletivo.exists():
            qcoletivo = qcoletivo.first()
        else:
            return HttpResponse('<h1>Page not found</h1>')

        if qindividual.exists():
            qindividual = qindividual.first()
        else:
            return HttpResponse('<h1>Page not found</h1>')

        context = {
            'inscricao': q,
            'inscricoes': all_inscricoes,
            'inscricaocoletiva': qcoletivo,
            'inscricoescoletivas': all_inscricoescoletivas,
            'inscricaoindividual': qindividual,
            'inscricoesindividuais': all_inscricoesindividuais,
            'escola': qescola,
            'escolas': all_escolas,
            'participante': qparticipante,
            'participantes': all_participantes,
            'atividade': qatividade,
            'atividades': all_atividades,
            'menu': qmenu,
            'menus': all_menus
        }

        return render(request, 'inscricoes/consultar_inscricao_responsaveis.html', context)


class ConsultarInscricaoEscola(DetailView):
    model = Escola
    template_name = 'inscricoes/consultar_inscricao_escola.html'

    def detail(request, inscricao_id):
        q = Inscricao.objects.filter(slug=inscricao_id)
        all_inscricoes = Inscricao.objects.all()
        all_inscricoescoletivas = Inscricaocoletiva.objects.all()
        qcoletivo = Inscricaocoletiva.objects.filter(slug=inscricao_id)
        qindividual = Inscricaoindividual.objects.filter(slug=inscricao_id)
        all_inscricoesindividuais = Inscricaoindividual.objects.all()
        qescola = EscolaForm.objects.filter(slug=inscricao_id)
        all_escolas = EscolaForm.objects.all()
        qparticipante = ParticipanteForm.objects.filter(slug=inscricao_id)
        all_participantes = ParticipanteForm.objects.all()
        qatividade = Atividade.objects.filter(slug=inscricao_id)
        all_atividades = Atividade.objects.all()
        qmenu = Inscricaoprato.objects.filter(slug=inscricao_id)
        all_menus = Inscricaoprato.objects.all()

        context = {
            'inscricao': q,
            'inscricoes': all_inscricoes,
            'inscricaocoletiva': qcoletivo,
            'inscricoescoletivas': all_inscricoescoletivas,
            'inscricaoindividual': qindividual,
            'inscricoesindividuais': all_inscricoesindividuais,
            'escola': qescola,
            'escolas': all_escolas,
            'participante': qparticipante,
            'participantes': all_participantes,
            'atividade': qatividade,
            'atividades': all_atividades,
            'menu': qmenu,
            'menus': all_menus
        }

        return render(request, 'inscricoes/consultar_inscricao_escola.html', context)

    def escola(request):
        inscricoes = Inscricao.objects.filter(
            writingdate__lte=timezone.now()).order_by('writingdate')
        locais = Escola.objects.all()
        return render(request, 'inscricoes/consultar_inscricao_escola.html', {'inscricoes': inscricoes, 'locais': locais})

    def transporte(request):
        return render(request, 'inscricoes/consultar_inscricao_transporte.html')

    def almoço(request):
        return render(request, 'inscricoes/consultar_inscricao_almoço.html')

    def sessoes(request):
        return render(request, 'inscricoes/consultar_inscricao_sessao.html')


def ConsultarInscricoesAntigo(request: HttpRequest):
    pass


def detail(request, inscricao_id):
    q = Inscricao.objects.filter(slug=inscricao_id)
    all_inscricoes = Inscricao.objects.all()
    all_inscricoescoletivas = Inscricaocoletiva.objects.all()
    qcoletivo = Inscricaocoletiva.objects.filter(slug=inscricao_id)
    qindividual = Inscricaoindividual.objects.filter(slug=inscricao_id)

inscricoes/templates/inscricoes/alterar_inscricao.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Consultar Inscrição</title>
</head>

<body>
    {% comment %} <form method="post">
        {% csrf_token %}
        <h2>Alterar Inscrição</h2>
        <hr>

        {% for inscricao in inscricoes %}
        <table>
            <tr>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricao.local}}</a></td>
            </tr>
        </table>
        {% endfor %}

        {% for escola in inscricoes %}
        <table>
            <tr>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ escola.nome}}</a></td>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ escola.local}}</a></td>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ escola.telefone}}</a></td>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ escola.email}}</a>
            </tr>
        </table>
        {% endfor %}

        {% for inscricaocoletiva in inscricoes %}
        <table>
            <tr>
                <h4>Num Alunos:</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaocoletiva.nalunos}}</a></td>
                <h4>Num responsaveis:</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaocoletiva.nresponsaveis}}</a></td>

            </tr>
        </table>
        {% endfor %}

        {% for inscricaoindividual in inscricoes %}
        <table>
            <tr>
                <h4>Num acompanhantes:</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaoindividual.nacompanhantes}}</a></td>

            </tr>
        </table>
        {% endfor %}

        {% for inscricaoprato in inscricoes %}
        <table>
            <tr>
                <h4>Prato</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaoprato.prato}}</a></td>
                <h4>Num pessoas</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaoprato.npessoas}}</a></td>
            </tr>
        </table>
        {% endfor %}

    
        <table class="table">
            <tr>
                <th>Nome da Atividade</th>
                <th>Nº Sessões</th>
            </tr>
            {% for atividade in atividades %}
            <tr>
                <td>{{atividade.nome}}</td>
                <td>{{atividade.sessao_set.count}}</td>
            </tr>
            {% endfor %}
        </table>

        {% for inscricaosessao in inscricoes %}
        <table>
            <tr>
                <h4>Sessão:</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaosessao.sessao}}</a></td>
                <h4>Num participantes numa sessão</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaosessao.nparticipantes}}</a></td>
            </tr>
        </table>
        {% endfor %}
    
        {% for inscricaotransporte in inscricoes %}
        <table>
            <tr>
                <h4>Transporte::</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaotransporte.transporte}}</a></td>

                <h4>Num passageiros:</h4>
                <td><a href="{% url 'InscricaoUpdate' inscricao_id=inscricao.id %}">{{ inscricaotransporte.npassageiros}}</a></td>
            </tr>
        </table>
        {% endfor %}
    

        <h4>Almoço - Num de Pratos:</h4>
        {{ Inscricaotransporte.npassageiros}}
        <hr>

        <h4></h4>

        <button type="submit">Submeter</button>
        </form> {% endcomment %}
        {% endblock content %}
</body>

</html>

inscricoes/templates/inscricoes/consultar_inscricao_responsaveis.html
{% extends 'app.html' %}
{% load i18n %}

{% block load %}
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha256-pasqAKBDmFT4eHoN2ndd6lN370kFiGUFyTiUHWhU7k8=" crossorigin="anonymous"></script>
{{ wizard.form.media }}
{% endblock %}

{% block scripts %}
<script>
    $("input").addClass("input");
</script>
{% endblock scripts %}

{% block title %}Inscrição{% endblock title %}

{% block content %}
<div>
    <nav aria-label="breadcrumbs" class="breadcrumb">
        <ul>
            <li><a href="/" class="router-link-active">Início</a></li>
            <li class="is-active"><a href="/inscricao" class="router-link-exact-active router-link-active">Minha
                    Inscrição</a></li>
        </ul>
    </nav>
    <div style="padding: 3rem 2vw 1rem;">
        <div class="steps is-success">
            <div class="step-item is-success is-active">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-account"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Responsáveis</p>
                </div>
            </div>
            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-school"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Escola</p>
                </div>
            </div>
            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-train-car"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Transporte</p>
                </div>
            </div>
            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-food-apple"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Almoço</p>
                </div>
            </div>
            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-calendar-check"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Sessões</p>
                </div>
            </div>
            <div class="step-item is-success">
                <div class="step-marker">
                    <span class="icon">
                        <i class="mdi mdi-check"></i>
                    </span>
                </div>
                <div class="step-details">
                    <p class="step-title">Submissão</p>
                </div>
            </div>
        </div>
        <hr />
        <form action="" method="post">
            {% csrf_token %}
            {{ wizard.management_form }}
            <h2 class="title has-text-grey is-uppercase" style="font-size: 0.9rem">
                Docente Responsável 1
            </h2>
            <div class="columns">
                <div class="column">
                    <div class="field">
                        <label for="{{ form.nome.id_for_label }}" class="label">Nome</label>
                        <div class="controlis-clearfix">{{object.participante.first_name}} {{object.participante.last_name}}</div>
                        {{ form.nome.errors }}
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label for="{{ form.email.id_for_label }}" class="label">E-mail</label>
                        <div class="control is-clearfix">{{object.participante.email}}</div>
                        {{ form.email.errors }}
                    </div>
                </div>
                <div class="column">
                    <div class="field">
                        <label for="{{ form.tel.id_for_label }}" class="label">Telemóvel/Telefone</label>
                        <div class="control is-clearfix">{{object.inscricaocoletiva.escola.telefone}}</div>
                        {{ form.tel.errors }}
                    </div>
                </div>
            </div>
            <hr />
            <div class="column is-8 is-offset-2">
                <div class="level">
                    <div class="level-left">
                        {% if wizards.steps.prev %}
                        <button class="button is-outlined" name="wizard_goto_step" value="{{ wizard.steps.prev }}">
                            <span class=" icon is-small"><i class="mdi mdi-chevron-left"></i></span>
                            <span>Anterior</span>
                        </button>
                        {% endif %}
                    </div>
                    <div class="level-right">
                        <a href="{% url 'escola' %}">
                            <span>Próximo</span>
                            <span class="icon is-medium"><i class="mdi mdi-forward mdi-36px"></i></span>
                        </a>
                    </div>
                </div>
            </div>
        </form>
    </div>

{% endblock content %}
</div>

inscricoes/templates/inscricoes/consultar_inscricoes.html
{% extends 'app.html' %}
{% block title %}Consultar Inscrição{% endblock title %}

{% block content %}

        <div>
                <nav aria-label="breadcrumbs" class="breadcrumb">
                    <ul>
                        <li><a href="/" class="router-link-active">Início</a></li>
                        <li class="is-active"><a href="/inscricao" class="router-link-exact-active router-link-active">Inscrições</a></li>           
                                 </ul>
                </nav>
     
        {% csrf_token %}
       
<p>Filtrar por:</p>

<form action="PageObjects" method="post">
        <b>Departamento</b>
         <select id="departamento">
          <option value="departamento">FCT</option>
          <option value="departamento">FCHS</option>


        </select>
</form>

<form action="PageObjects" method="post">
        <b>Hora</b>
        <select id="hora">
         <option value="hora">09:00</option>
         <option value="hora">10:00</option>
         <option value="hora">10:30</option>
       </select>
</form>


<form action="PageObjects" method="post">
        <b>Área Científica</b>
        <select id="hora">
         <option value="hora">Matemática</option>
         <option value="hora">Ciências</option>
         <option value="hora">Economia</option>
       </select>
</form>

<form action="PageObjects" method="post">
        <b>Tipo</b>
        <select id="hora">
         <option value="hora">Atividades Experimentais</option>
         <option value="hora">Demonstrações</option>
         <option value="hora">Atividades investigativas</option>
       </select>
</form>
        
        {% load django_tables2 %}
        {% render_table table %}

        {% endblock content %}
</div>

inscricoes/templates/inscricoes/criar_inscricao_coletiva.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inscrição - Dia Aberto</title>
</head>

<body>
    <form method="post">
        {% csrf_token %}
        <h2>Criar Inscrição coletiva</h2>
        <hr>
        <h4>Professor:</h4>
        {{ participante_form.as_p }}
        <hr>
        <h4>Escola:</h4>
        {{escola_form.as_p}}
        <hr>
        <h4>Inscrição:</h4>
        {{ inscricao_form.as_p }}
        <button type="submit">Inscrever</button>
    </form>
</body>

</html>